scverse/spatialdata-plot

src/spatialdata_plot/pp/basic.py
Needs more unti tests, don't merge yet
=> Improves get_channels

tests/conftest.py, tests/test_pp.py
* checks for input types and every type/value assertion is raised correctly in `pp.get_bb`
=> Tests for pp.get_bb

.pre-commit-config.yaml, src/spatialdata_plot/pl/basic.py, src/spatialdata_plot/pl/render.py
Now casting cell_ids to int which fixes an edge-case.
Also sped up the plotting for random colors
=> Bugfix and Speedup for `render_labels`

.cruft.json, .github/workflows/build.yaml, .github/workflows/sync.yaml, .github/workflows/test.yaml, .github/workflows/test.yaml.rej, docs/conf.py, docs/contributing.md, docs/references.bib, pyproject.toml.rej, src/spatialdata_plot/pp/basic.py.rej, tests/test_basic.py.rej
This PR fixes some problems with the CI setup of the scverse-cookiecutter template repo. Last night, [the `codecov` package was pulled from PyPI](https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259). This can easily be replaced, however we've realized our automatic template sync system does not allow us to modify github actions (a security precaution from github), so we need to roll out this update manually.
We're also taking this opportunity to make several other intended changes for to the CI workflow.
We're still looking into how we can avoid this in the future, which will likely require us changing how our template sync system works. This is being tracked in the [scverse/cookiecutter-scverse#138](https://www.github.com/scverse/cookiecutter-scverse/issues/138). …
=> Fix codecov CI and update template

.github/workflows/test_and_deploy.yaml, pyproject.toml
this PR adds deploy to github actions on pushing tags formatted as vx.x.x
=> add deploy to github actions

src/spatialdata_plot/pl/basic.py, src/spatialdata_plot/pl/render.py, src/spatialdata_plot/pl/utils.py
=> render_images now respects cmap when channels are used

README.md
Put only links to the spaitaldata-plot documentation as before it was mixed and a bit confusing.
=> fixed links in the docs

CHANGELOG.md
The correct version to release is 0.0.6, not 1.0.0.
=> corrected version number

src/spatialdata_plot/pl/utils.py
Add check + error message in `utils._get_colors_for_categorical_obs`
=> add error message for when len(palette)!=len(categories)

src/spatialdata_plot/pl/render.py
A `.values` attribute has been forgotten.
`label` is a SpatialImage and DataArray. Scikit-image expects a true array with a reshape method. All other uses of `_map_color_seg` pass the correct value, e.g.:
https://github.com/scverse/spatialdata-plot/blob/09a31adec012483d1bc578a1fa4802ce8e8b8046/src/spatialdata_plot/pl/render.py#L618-L620
=> Fix "xarray has no attribute reshape"

src/spatialdata_plot/pl/basic.py, src/spatialdata_plot/pl/render.py, src/spatialdata_plot/pl/render_params.py, src/spatialdata_plot/pl/utils.py
=> Partial fixes mypy

.github/workflows/test_and_deploy.yaml, src/spatialdata_plot/pl/basic.py, src/spatialdata_plot/pl/render.py, src/spatialdata_plot/pl/render_params.py, src/spatialdata_plot/pl/utils.py, src/spatialdata_plot/pp/basic.py, src/spatialdata_plot/pp/utils.py, tests/conftest.py, tests/pl/test_render_labels.py, tests/pl/test_render_points.py, tests/pl/test_render_shapes.py
PR to support the multi_table specification of SpatialData
=> allow for plotting using specific table (#217)

.github/workflows/test_and_deploy.yaml, .readthedocs.yaml, pyproject.toml
The docs in main build even if the code is using functions not available in `spatialdata-0.0.16` (but available in the latest pre-release). This could be due to the fact when building the docs only, the only .py files that are imported are not importing functions available only in the pre-release. Same for the tests, maybe the new functions are not covered by tests.
Anyway, I am merging preventively this PR.
=> Enabling tests and docs against spatialdata pre-release

src/spatialdata_plot/pl/utils.py
This PR fixes an issue that was appearent in the spatial query notebook. Fix for color was not properly checked when there was no table annotating a particular element and color was specified. This fixes the issue by having a safety check when the table mapping value is an empty set and thus the for loop code is not run
=> fix_col_for_color

.gitignore, src/spatialdata_plot/pl/utils.py
The `fill_alpha` parameter was overwriting the alpha values in an eventual colormap passed by the user. This PR fixes it.
=> Fix fill alpha ignoring alpha from colormaps

src/spatialdata_plot/pl/basic.py, src/spatialdata_plot/pl/render.py, src/spatialdata_plot/pl/render_params.py
Provides basic datashader support for ShapeElements. Still needs to address other parameters (outlines an such), but proof of concept works!
Example rendering 2389 polygons from merfish dataset:
Using matplotlib (22.4s):
Using datashader (6.6s):
=> basic shapes datashader rendering

src/spatialdata_plot/pl/render.py, src/spatialdata_plot/pl/utils.py
closes #234 
Follow up on #235 fixing the plotting color columns that are numerical. First this fixes the visibility of the colorbar when plotting labels with a color. The issue here was that due to the outline_alpha being set to 0 when outline is False and outline of the label being plotted after the labels it would overwrite the colorbar. This was fixed by first plotting outline and then the label. A potential issue here is that when both alpha and outline alpha are 1 the outline will not be visible, but currently I thought this best as there is no clear way to decouple the colorbar from the outline. The general rule here is whatever is plotted last is visible.
The other issue got reported by @LucaMarconato  in #234 . Ultimately, this was an issue when plotting `feature0` in the …
=> Fix var plotting

src/spatialdata_plot/_utils.py, src/spatialdata_plot/pl/basic.py, src/spatialdata_plot/pl/render.py, src/spatialdata_plot/pl/render_params.py, src/spatialdata_plot/pl/utils.py
This PR refactors the way the parameters for image rendering get validated and passed. Some of the changes are not backward compatible. For `element` the user can't pass on a `list` of `str` anymore, but only `str` or `None`. All the passed on parameters are used to create a view config for a single element. If `element` is `None` then all the parameters are checked for whether they are valid for a specific element and if that is not the case the value of the parameter for that element is set to None. If a user wants to plot multiple specific images, the `pl.render` calls can be chained. 
Because of creating viewconfigs in such a way that each element has its own contained config this will make it easy to hook up vega like specifications and also to write those out.
=> Image render param refactor

src/spatialdata_plot/pl/basic.py, src/spatialdata_plot/pl/render.py, src/spatialdata_plot/pl/utils.py, src/spatialdata_plot/pp/basic.py, tests/conftest.py, tests/pl/test_get_extent.py, tests/pl/test_render_images.py, tests/pl/test_render_labels.py, tests/pl/test_render_points.py, tests/pl/test_render_shapes.py, tests/pl/test_show.py, tests/pl/test_utils.py
With the SpatialImage and MultiscaleSpatialImage dependency changing we need to update the repo to account for this. See [#587](https://github.com/scverse/spatialdata/pull/587).  Also the PR adjusts to some of the newest changes on the spatialdata repo such as the changes to `locate_value`
Also this PR makes some changes in order to silence warnings.
This PR requires a release of spatialdata.
=> Adjusts spatialdata-plot to use DataArray and DataTree

src/spatialdata_plot/pl/basic.py
Labels were still being plotted even when `wanted_elements_on_this_cs` was an empty list due to this particular code block not being in the if conditional block. This test fixes that.
=> implement label fix

src/spatialdata_plot/pl/basic.py, src/spatialdata_plot/pl/utils.py
Due to seg having an empty first dimension, the calculation of seg_boundaries would fail as array shapes do not match. This PR fixes that issue.
=> Fix labels boundaries

src/spatialdata_plot/pl/render.py
There was a bug in the xernium notebook due to `sel` being used to select the channel even when the channel was `int`.
=> isel when channel is int

src/spatialdata_plot/pl/render.py
=> fix performance bug shapes

CHANGELOG.md, src/spatialdata_plot/pl/utils.py, tests/pl/test_render.py
Delegates the check whether an element exists upstream to `spatialdata`
=> Added error handling for non-existent elements

.pre-commit-config.yaml
The default stages are deprecated. This PR implements changes to avoid the warning of having to migrate the config.
=> migrate pre-commit config

.github/workflows/test.yaml, .mypy.ini, pyproject.toml, src/spatialdata_plot/pl/basic.py, src/spatialdata_plot/pl/render.py, src/spatialdata_plot/pl/render_params.py, src/spatialdata_plot/pl/utils.py, tests/conftest.py, tests/pl/test_utils.py
This PR fixes the issue of the deprecated `datatree` library now xarray directly supports `DataTree`. This PR will be dependent on a `SpatialData` release which in turn depends on a release of `multiscale-spatial-image`.
=> support for datatree from xarray

.pre-commit-config.yaml, src/spatialdata_plot/config.py, src/spatialdata_plot/pl/_viewconfig.py, src/spatialdata_plot/pl/basic.py, tests/conftest.py, tests/pl/test_get_extent.py, tests/pl/test_render_labels.py, tests/pl/test_render_points.py, tests/pl/test_render_shapes.py
During the Basel hackathon, @melonora @keller-mark @Sonja-Stockhaus and I, started working on view configurations to streamline the plotting experience. Specifically @melonora is working on functions to generate some preliminary view configuration from the `spatialdata-plot` plotting tree. This work is available in the branch `viewconfig`. 
This PR (ready to merge, since it's opened against the [`viewconfig`](https://github.com/scverse/spatialdata-plot/tree/viewconfig) branch), modifies the test configuration to automatically generate the view configurations for each test plot and save them in `tests/figures_viewconfig`. To view such view configurations please run the tests (I haven't included the view configurations in this PR since they are still very work-in-progress).
In the …
=> Generating and saving view configs from tests

src/spatialdata_plot/pl/render.py, src/spatialdata_plot/pl/utils.py, tests/pl/test_render_labels.py
The test `test_plot_coloring_with_cmap` in the tests for points was wrongly passing. When switching from the use of `get_categorical_obs` to `_get_categorical_color_mapping`, the `cmap` was not anymore in the arguments. This led to the default colors always being used despite a colormap being defined. This PR fixes that issue by updating `_get_categorical_color_mapping`.
On main:
With this PR:
=> Fix unused cmap in render_points

src/spatialdata_plot/pl/render.py
closes: #447 
In render shapes, when using datashader, all transforms were obtained instead of the transform to the coordinate system which is supposed to be rendered. This was a problem for the visium notebook when trying the following code snippet:
```
import spatialdata as sd
import spatialdata_plot  
import matplotlib.pyplot as plt
sdata = sd.read_zarr("C:\\Users\\w-mv\\PycharmProjects\\spatialdata-notebooks\\notebooks\\examples\\visium_hd.zarr")
plt.figure(figsize=(10, 10))
ax = plt.gca()
gene_name = "AA986860"
sdata.pl.render_shapes("Visium_HD_Mouse_Small_Intestine_square_016um", color=gene_name, method="datashader").pl.show(
coordinate_systems="Visium_HD_Mouse_Small_Intestine", ax=ax
)
```
After fixing that, the transform was applied and again parsed by `ShapesModel`. This ensured …
=> Get one shape transform

src/spatialdata_plot/pl/utils.py, tests/conftest.py, tests/pl/test_render_labels.py, tests/pl/test_render_points.py, tests/pl/test_render_shapes.py, tests/pl/test_utils.py
This PR ensures that spatialdata-plot works with the version of SpatialData on the zarrv3 branch.
=> make ready for new spatialdata
